### ISSUE TITLE
AsyncUniTaskMethodBuilder doesn't implement ObjectIdForDebugger which can cause crashes

### ISSUE THREAD

**Issue by UnityAlex** [Cysharp/UniTask#66]
I've been investigating: https://issuetracker.unity3d.com/issues/crash-when-performing-step-over and discovered that the crash was due to the mono debugger hitting an assert when it failed to find the ObjectIdForDebugger accessor within the async builder class. I will attempt to prevent the debugger from crashing on my side but without this implemented the debugger will not function as intended.

**Comment by neuecc** [comment]
Thank you for clarification.
Indeed, corelib's source code says so.
However, for example, I've added the following to `AssyncUniTaskVoidMethodBuilder`.

```csharp
private Task m_task;  // AscynValueTaskMethodBuilder said Debugger depends on the exact name of this field.

// Add this for debugger
public object ObjectIdForDebugger { get { return m_task ?? (m_task = new Task(() => { })); } }
```

It still crashes.
Do you know any other information?

**Comment by neuecc** [comment]
in EditorLog, shows
`* Assertion at ..\mono\mini\debugger-agent.c:5433, condition `array->len == 1' not met`
and (probably) this line?
https://github.com/Unity-Technologies/mono/blob/25cf110b679af710b41f6a2dc92753012a38d629/mono/mini/debugger-agent.c#L5441
(I don't know which revision is valid version of mono in Unity 2019.3.9f1...)

**Comment by UnityAlex** [comment]
Yes that's the assert that I was seeing hit when I reproduced the issue. I will have to try your fix to see why it is still continuing to crash. I assume you put it within the struct yes? Similar to: https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs#L704

**Comment by neuecc** [comment]
It was prevented to fall with only `ObjectIdForDebugger` thank you.
(The reason it didn't work when I tried it above may be that I did something wrong, the DLL wasn't recompiled...)

In UniTask, since the task is structured, I decided to return a dummy object once.

```csharp
#if UNITY_EDITOR
        // Important for IDE debugger.
        Private object ObjectIdForDebugger;
        private object ObjectIdForDebugger
        {
            get
            {
                if (debuggingId == null)
                {
                    debuggingId = new object();
                }
                return debuggingId;
            }
        }
#endif
```

Now I was able to debug successfully in Unity 2019.3.9f1 + Visual Studio 2019 combination.
I've released this as ver.1.3.1.

**Comment by UnityAlex** [comment]
Sounds great! Thanks!

**Comment by fnuecke** [comment]
Out of curiosity: why `UNITY_EDITOR` and not `DEBUG`? Does the debugger behave differently when attached to standalone builds in this context?

**Comment by neuecc** [comment]
I thought that UnityEditor is the main scenario of attach in the IDE debugger.
If you want DEBUG, I'll change it to DEBUG.
More ideally, don't use object that only used in debugging, I'm going to change that in the future.

**Comment by fnuecke** [comment]
It definitely is the main scenario! It just happens every so often that I need to debug a dev build because of bugs that simply don't happen in the editor, so that's why I'm also interested in having debug work in dev builds. Since with `DEBUG` it'd still get stripped in release builds, I was just wondering if there was a specific reason to limit this to the editor :)
